### ISSUE TITLE
Horion Downloading RATs?

### ISSUE THREAD

**Issue by SFODWings** [horionclient/Horion#227]
I was on discord looking for the Horion discord when I realized it was deleted. I thought "hmm, that's weird. maybe they got shut down I'll go look to see if there's a new discord link on the injector." I open it up and my antivirus detects a RAT. It never had this problem before. I've always had that antivirus on and it never stopped Horion from working. Until now. You guys have build up a huge group of people who use your injector. My thought process is as follows. You deleted the discord server, so no one can talk to each other. You update the injector but put a RAT in it, and tell people to turn their anti virus off so it'll work. I understand the importance of turning off an antivirus. false positives. but given the recent events, I'd it's pretty likely that they did put a RAT in the injector because your antivirus is turned off which means there's no way to detect it. It's a perfect front. I also found a malicious file in their download website, that wasn't the injector. Besides, if it was a false positive then why would it pick up a RAT? I suspect Horion is up to no good. Also, the older version Isn't working anymore, forcing people to use the new one. Be careful everyone.

**Comment by SFODWings** [comment]
Besides, if it was a false positive then why would it pick up a RAT?

**Comment by Headstabberz** [comment]
"Hello, patrons,



I have to apologize. As you may have noticed from Survivors post, our discord server got deleted. This has caused our backend to stop working, which is why you can't access the beta anymore at the moment.

We have a new discord server, but I don't trust discord anymore. I will take a closer look at Patron's API and try to fix it without using discord.

I'm really sorry to cause you such trouble.

The server has always been a time bomb, we knew it would be deleted eventually. However, we fully relied on it without providing any alternatives.

I'm looking for an alternative to Discord, but it may take time to get all this done. If you know any good alternatives, answer this post below!



I'm glad that we have achieved something like this so far. It may be the end of Horion on Discord, but not the end of Horion in general. We will continue to work on improving the mod, even if it will be delayed due to the above mentioned points, but we will do our best.



In this sense, thank you,

Richard "

**Comment by Headstabberz** [comment]
Discord server
The horion club discord has been terminated by discord for breaking TOS .

We are sorry about the inconvenience a new server will be ready soon. from the patreon not sure
just compile your own DLL's

**Comment by enescaglayan** [comment]
im not having any issues with it currently

**Comment by enescaglayan** [comment]
i can give you my own version that i downloaded yesterday if you want
