### ISSUE TITLE
When i inject it crashes minecraft.

### ISSUE THREAD

**Issue by FreeVideo11** [horionclient/Horion#471]
When I go on Minecraft and inject it to Minecraft it crashes it I think it's because Minecraft got a new update.

**Comment by Mixu78** [comment]
Everyone knows about this idiot

**Comment by HAXORWAXOR** [comment]
Due to the latest Minecraft update (1.16.100), horion is currently not working. To get around this issue, you can downgrade Minecraft! There are 2 methods for you to choose from.
1: Go to https://github.com/MCMrARM/mc-w10-version-launcher/releases/download/0.1.0/MCLauncher.zip and run the program. the Minecraft version you want to select is "1.16.40". once downloaded, you will have an older appx, navigate to it and double click to install.
2: Go to https://www.mediafire.com/file/d9ae6u2nyijt1sf/Minecraft-1.16.40.2.Appx/file and download, then double click to install the older version of Minecraft!

**Comment by FreeVideo11** [comment]
thanks HAXORWAXOR

**Comment by Mixu78** [comment]
Close this issue smh

**Comment by FreeVideo11** [comment]
Mixu78 what the hell is your problem

**Comment by Mixu78** [comment]
You opening 1. Useless issue and 2. Duplicate of #468

**Comment by HAXORWAXOR** [comment]
just close the issue you retard

**Comment by Mixu78** [comment]
Agree
